### ISSUE TITLE
aarch64 platform failure

### ISSUE THREAD

**Issue by maursam** [fmidev/docker-smartmetserver#3]
Hello, 
I'm trying to build an image for the aarch64 platform but when is looking for this file 

#4 13.39 failure: repodata/repomd.xml from smartmet-open: [Errno 256] No more mirrors to try.
#4 13.39 https://download.fmi.fi/smartmet-open/rhel/7/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

it not exists, in deed, there are no files for this architecture.
So, the question is, is there a possibility to build an image for aarch64 architecture?.

**Comment by apavenis** [comment]
There are only x86_64 packages on [https://download.fmi.fi](https://download.fmi.fi). I do not know whether somebody else has built packages for aarch64

You may try to build then yourself.
My recently written  [PERL script ](https://github.com/fmidev/smartmet-utils/blob/master/smartbuild) may help.
Resolving all dependencies will also require work: look for SRPMS in smartmet-open-ext repo. SPEC files of some of them may require changes.
